name: Laravel

on:
  push:
    branches: [ master, bobpos-dev]
  pull_request:
    branches: [ master, bobpos-dev]

jobs:
  laravel-tests:
    
    runs-on: ubuntu-latest
    services:
      mysql:
          image: mysql:5.7
          env:
              MYSQL_ALLOW_EMPTY_PASSWORD: true
              MYSQL_DATABASE: laravel
          ports:
              - 3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: password
    steps:  
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '8.1'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Start mysql service
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' --user=${{ env.DB_USER }} --password=${{ env.DB_PASSWORD }}
    - name: Create Database File
      run: touch tests/database.sqlite
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create a delay for mysql to start
      run: sleep 30
    - name: Run MySQL test 2
      run: mysql --user=root --host=127.0.0.1
      continue-on-error: true
    - name: Run MySQL Test
      run: mysql --user=laravel --host=127.0.0.1
      continue-on-error: true
    - name: Run Migrations
      run: php artisan migrate --path=./database/migrations/core,./database/migrations/create --seed
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit --config phpunit.ci.xml
      env:
        DB_CONNECTION: mysql
        DB_HOST: mysql
        DB_DATABASE: laravel
        DB_USERNAME: laravel
        DB_PASSWORD: 
        DB_PORT: ${{ job.services.mysql.ports['3306'] }}